"""fix error in kanban models

Revision ID: db21ccfd03a0
Revises: 61637f210744
Create Date: 2026-02-20 12:42:51.987347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db21ccfd03a0'
down_revision: Union[str, Sequence[str], None] = '61637f210744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
